language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install flake8
- pip install setuptools==49.2.0
script:
- python setup.py test
deploly:
  provider: pypi
  username: "__token__"
  password:
    secure: qrP/vr8OEIvHOK8SxIkKO5hSUXk+/8W3MIWQIpan4YelCktN5lrWS0v8Ht/fFcyzzPAvyL0aJYLur+iQpwsAT53PaKNTjSJtHes3dV+MXSHpsDnRNsRW9dq84AapjKc41oeG6/Exqez0V6/NEI5FRVJFb5j2bRAUnMdxSRlnzNrEmXIwb9RRnbhuR+CP9GENsdS3NAknMlkVBt0pJlanA1O36KUVFWlJYYAyl2X5xmQBjWerRLfcPJWGJcGFyhIFXZHWoLgWvdYFV/8/7yrpftplnfDHLuk2yaB391xwITQ3pbghzX9cUx4IVYhre5WU6j8gWjQp+9CV4by0hbdLSad6kZL/bgjIj/LH2jjCklgnUJ0e7tXQgGzgvTzo4Q2vj1V9GmGD0SLKP6IG8V+erUc3rqsO5qvvjQkpBHTHKKZGydbi8+YDzmkuMWQZrkydl9/n8DtCyAUg2xzYrGAI1fk5jdFSZF/CutTcLC4tf8QLoZxN/EnOocEPK64jnXOTKvrDOVuog0zTy7TbSftED0Ois6KkG0jLIHHqyj/csuq6C/pW1aJj5QQEs2PzotGpR1NzlZRxKckc+lx/n9nO3ilvrll39DIStsmmdVBIFgVTZMxA9NskPyKzufwB8cgR5RbCxipsib4zwX7IfVZqdACH4wq6wgUx5WEbStAE2No=
  on:
    tags: true
  skip_cleanup: true
  skip_existing: true
